const myPortfolio={user:'@MyFinCity',bank:'Swissquote',capital:100000,ret:18.7,risk:2,allocation:[45,30,15,10]};
const investment=[
{id:1,name:'Mein Gebäude · Enge',holder:'@MyFinCity',ret:18.7,risk:2,lng:8.5298,lat:47.3608,kind:'owned',allocation:[45,30,15,10],slots:6,occupied:4,lastAuctionPrice:520,lastAuctionDate:'14.08.2026'},
{id:2,name:'Seefeld Residenz',holder:'@LakeAlpha',ret:12.9,risk:1,lng:8.5445,lat:47.3577,kind:'active',allocation:[70,0,20,10],slots:2,occupied:2,lastAuctionPrice:650,lastAuctionDate:'17.07.2026'},
{id:3,name:'Wiedikon Stadthaus',holder:'@ZuriValue',ret:24.6,risk:4,lng:8.5228,lat:47.3692,kind:'active',allocation:[45,40,5,10],slots:8,occupied:6,lastAuctionPrice:760,lastAuctionDate:'31.07.2026'},
{id:4,name:'Oerlikon Wohnhaus',holder:'@HelveticGrowth',ret:16.3,risk:3,lng:8.5437,lat:47.4092,kind:'active',allocation:[60,15,15,10],slots:12,occupied:9,lastAuctionPrice:980,lastAuctionDate:'07.08.2026'},
{id:5,name:'Altstetten Wohnblock',holder:'@LimmatInvestor',ret:9.8,risk:2,lng:8.4879,lat:47.3821,kind:'active',allocation:[65,0,20,15],slots:18,occupied:11,lastAuctionPrice:690,lastAuctionDate:'03.07.2026'},
{id:6,name:'Höngg Anlagehaus',holder:'@NorthStarZH',ret:21.1,risk:3,lng:8.5006,lat:47.4010,kind:'active',allocation:[55,25,10,10],slots:10,occupied:8,lastAuctionPrice:840,lastAuctionDate:'28.08.2026'},
{id:7,name:'Wollishofen Wohnhaus',holder:'@BlueLake',ret:11.6,risk:2,lng:8.5370,lat:47.3388,kind:'active',allocation:[60,0,25,15],slots:5,occupied:4,lastAuctionPrice:470,lastAuctionDate:'19.06.2026'},
{id:8,name:'Hottingen Stadthaus',holder:'@ZurichCore',ret:28.4,risk:5,lng:8.5625,lat:47.3689,kind:'active',allocation:[35,50,5,10],slots:7,occupied:7,lastAuctionPrice:1450,lastAuctionDate:'24.07.2026'},
{id:9,name:'Unterstrass Wohnhaus',holder:'@YieldPilot',ret:14.7,risk:2,lng:8.5440,lat:47.3923,kind:'active',allocation:[70,0,15,15],slots:9,occupied:5,lastAuctionPrice:610,lastAuctionDate:'12.06.2026'},
{id:10,name:'Albisrieden Wohnblock',holder:'@SwissCompound',ret:19.8,risk:3,lng:8.4976,lat:47.3737,kind:'active',allocation:[55,20,15,10],slots:14,occupied:10,lastAuctionPrice:890,lastAuctionDate:'05.06.2026'},
{id:11,name:'Aussersihl Stadthaus',holder:'@UrbanAlpha',ret:31.2,risk:5,lng:8.5225,lat:47.3794,kind:'active',allocation:[30,55,5,10],slots:11,occupied:9,lastAuctionPrice:1210,lastAuctionDate:'21.08.2026'},
{id:12,name:'Fluntern Wohnhaus',holder:'@PeakCapital',ret:10.9,risk:1,lng:8.5637,lat:47.3813,kind:'active',allocation:[75,0,15,10],slots:4,occupied:3,lastAuctionPrice:730,lastAuctionDate:'29.05.2026'},
{id:13,name:'Schwamendingen Wohnblock',holder:'@CityBeta',ret:17.5,risk:4,lng:8.5701,lat:47.4047,kind:'active',allocation:[45,35,10,10],slots:20,occupied:13,lastAuctionPrice:1020,lastAuctionDate:'22.05.2026'},
{id:14,name:'Mein Gebäude · Höngg',holder:'@MyFinCity',ret:18.7,risk:2,lng:8.4979,lat:47.4026,kind:'owned',allocation:[45,30,15,10],slots:10,occupied:7,lastAuctionPrice:580,lastAuctionDate:'10.07.2026'},
{id:15,name:'Mein Gebäude · Wollishofen',holder:'@MyFinCity',ret:18.7,risk:2,lng:8.5330,lat:47.3376,kind:'owned',allocation:[45,30,15,10],slots:5,occupied:3,lastAuctionPrice:410,lastAuctionDate:'26.06.2026'}
];
const auctions=[
{id:101,name:'Enge Stadthaus',address:'Bederstrasse 77, 8002 Zürich',slots:4,lng:8.5272,lat:47.3617,date:'Freitag · 20:00 Uhr'},
{id:102,name:'Wiedikon Wohnhaus',address:'Birmensdorferstrasse 241, 8003 Zürich',slots:8,lng:8.5088,lat:47.3714,date:'Freitag · 20:00 Uhr'},
{id:103,name:'Oerlikon Wohnhaus',address:'Schaffhauserstrasse 355, 8050 Zürich',slots:10,lng:8.5433,lat:47.4098,date:'Freitag · 20:00 Uhr'},
{id:104,name:'Altstetten Wohnblock',address:'Badenerstrasse 681, 8048 Zürich',slots:16,lng:8.4838,lat:47.3827,date:'Freitag · 20:00 Uhr'},
{id:105,name:'Aussersihl Wohnblock',address:'Hohlstrasse 217, 8004 Zürich',slots:24,lng:8.5202,lat:47.3813,date:'Freitag · 20:00 Uhr'}
];
const trophies=[
{id:201,name:'Grossmünster',subtype:'Wahrzeichen',lng:8.5441,lat:47.3701,champion:{year:2027,user:'@LakeAlpha'}},
{id:202,name:'Fraumünster',subtype:'Wahrzeichen',lng:8.5414,lat:47.3698},
{id:203,name:'Uetliberg',subtype:'Wahrzeichen',lng:8.4914,lat:47.3495},
{id:204,name:'Zürich Hauptbahnhof',subtype:'Bahnhof',lng:8.540278,lat:47.377778},
{id:205,name:'Bahnhof Stadelhofen',subtype:'Bahnhof',lng:8.548611,lat:47.366667},
{id:206,name:'Paradeplatz',subtype:'Platz',lng:8.53886,lat:47.3697},
{id:207,name:'Bürkliplatz',subtype:'Platz',lng:8.54137,lat:47.3665},
{id:208,name:'Sechseläutenplatz',subtype:'Platz',lng:8.546764,lat:47.365414},
{id:209,name:'Lindenhof',subtype:'Wahrzeichen',lng:8.54045,lat:47.37308},
{id:210,name:'Opernhaus Zürich',subtype:'Wahrzeichen',lng:8.54686,lat:47.36503},
{id:211,name:'Kunsthaus Zürich',subtype:'Wahrzeichen',lng:8.54824,lat:47.37022},
{id:212,name:'ETH Hauptgebäude',subtype:'Wahrzeichen',lng:8.54805,lat:47.37633},
{id:213,name:'Universität Zürich',subtype:'Wahrzeichen',lng:8.54886,lat:47.37453},
{id:214,name:'Landesmuseum Zürich',subtype:'Wahrzeichen',lng:8.54069,lat:47.37917},
{id:215,name:'FIFA Museum',subtype:'Wahrzeichen',lng:8.53139,lat:47.36385},
{id:216,name:'Chinagarten Zürich',subtype:'Wahrzeichen',lng:8.55193,lat:47.35485},
{id:217,name:'Bellevue',subtype:'Platz',lng:8.5455,lat:47.36675},
{id:218,name:'Central',subtype:'Platz',lng:8.54439,lat:47.37662},
{id:219,name:'Rathaus Zürich',subtype:'Wahrzeichen',lng:8.5427,lat:47.37149},
{id:220,name:'Quaibrücke',subtype:'Wahrzeichen',lng:8.54375,lat:47.36585},
{id:221,name:'Polyterrasse',subtype:'Wahrzeichen',lng:8.54707,lat:47.37682},
{id:222,name:'Prime Tower',subtype:'Wahrzeichen',lng:8.51533,lat:47.38507},
{id:223,name:'Bahnhof Hardbrücke',subtype:'Bahnhof',lng:8.51715,lat:47.38512},
{id:224,name:'Stadion Letzigrund',subtype:'Wahrzeichen',lng:8.50455,lat:47.38294},
{id:225,name:'Helvetiaplatz',subtype:'Platz',lng:8.52625,lat:47.37574},
{id:226,name:'Werdinsel',subtype:'Wahrzeichen',lng:8.47965,lat:47.40069},
{id:227,name:'Zoo Zürich',subtype:'Wahrzeichen',lng:8.5743,lat:47.3857},
{id:228,name:'Museum Rietberg',subtype:'Wahrzeichen',lng:8.53,lat:47.35845},
{id:229,name:'Sukkulenten-Sammlung',subtype:'Wahrzeichen',lng:8.53668,lat:47.35653},
{id:230,name:'Irchelpark',subtype:'Wahrzeichen',lng:8.54845,lat:47.39748}
];
const panel=document.getElementById('panel');
const satBtn=document.getElementById('satBtn');
const mapBtn=document.getElementById('mapBtn');
let map=null;let markerRecords=[];
const free=p=>Math.max(0,(p.slots||0)-(p.occupied||0));
const slotFee=ret=>ret<10?1:ret<20?2:ret<30?3:4;
const startPrice=slots=>slots<=4?100:slots<=10?200:300;
const chf=n=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}).format(n);
function riskLabel(r){return['','Sehr tief','Tief','Mittel','Hoch','Sehr hoch'][r]||'–'}
function userBuildings(holder){return investment.filter(x=>x.holder===holder)}
function users(){const m=new Map();investment.forEach(p=>{if(!m.has(p.holder))m.set(p.holder,{holder:p.holder,ret:p.ret,risk:p.risk,allocation:p.allocation,buildings:0,slots:0,free:0});const u=m.get(p.holder);u.buildings++;u.slots+=p.slots;u.free+=free(p)});return [...m.values()]}
function closePanel(){panel.classList.remove('show')}
function openPanel(html){panel.innerHTML=`<button class="close" aria-label="Schliessen">×</button>${html}`;panel.classList.add('show');panel.querySelector('.close').onclick=closePanel}
function activeNav(view){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function allocationHtml(a){const labels=['Aktien / ETFs','Krypto','Edelmetalle & Rohstoffe','Cash'];return `<div class="allocation"><div class="donut"></div><div>${labels.map((x,i)=>`<div style="margin:7px 0"><div class="previewrow"><span>${x}</span><b>${a[i]}%</b></div><div class="bar"><i style="width:${a[i]}%"></i></div></div>`).join('')}</div></div><p class="note">Nur grobe Anlageklassen; einzelne Positionen werden nicht offengelegt.</p>`}
function showCity(){activeNav('city');closePanel();applyFilter('all')}
function showAuctions(){activeNav('auctions');openPanel(`<div class="eyebrow">CITY DROPS · ZÜRICH</div><h2>Auktionen</h2><p class="note">Demo-Auktionen. Produktionsdaten werden vor Freischaltung über offizielle Quellen wie GWR/EGID verifiziert.</p><div class="active-list">${auctions.map(a=>`<div class="active-row" data-auction="${a.id}"><div><strong>${a.name}</strong><div class="rankmeta">${a.address}</div><div class="rankmeta">${a.slots} Wohnungen / Slots · ${a.date}</div></div><div style="text-align:right"><div class="eyebrow">START</div><div class="price">${chf(startPrice(a.slots))}</div></div></div>`).join('')}</div><div class="card"><strong>Erstverkauf</strong><div class="note">100 % des Zuschlagspreises eines neu freigeschalteten digitalen FinCity-Gebäudes gehen an FinCity.</div></div>`);panel.querySelectorAll('[data-auction]').forEach(el=>el.onclick=()=>showAuction(+el.dataset.auction))}
function showAuction(id){const a=auctions.find(x=>x.id===id);if(!a)return;openPanel(`<div class="eyebrow">AUKTION · CITY DROP</div><h2>${a.name}</h2><div class="card"><div class="previewrow"><span>Adresse</span><b>${a.address}</b></div><div class="previewrow"><span>Gebäudegrösse</span><b>${a.slots} Wohnungen / Slots</b></div><div class="previewrow"><span>Anfangspreis</span><b>${chf(startPrice(a.slots))}</b></div><div class="previewrow"><span>Termin</span><b>${a.date}</b></div></div><div class="card"><strong>Erstverkauf · 100 % → FinCity</strong><div class="note">Digitale FinCity-Marktposition; kein Eigentum an der realen Immobilie.</div></div><button class="action" id="flyAuction">AUF KARTE ZEIGEN</button>`);document.getElementById('flyAuction').onclick=()=>{safeFly(a.lng,a.lat);closePanel()}}
function showActive(){activeNav('active');const rows=[...investment].sort((a,b)=>b.lastAuctionPrice-a.lastAuctionPrice);openPanel(`<div class="eyebrow">AKTIVE GEBÄUDE · GEBÄUDELISTE</div><h2>Gebäudeübersicht</h2><p class="note">Ein User kann mehrere Gebäude besitzen. Die Rendite gehört immer zum User-Depot, nicht zum einzelnen Gebäude.</p><div class="active-list">${rows.map((p,i)=>`<div class="active-row" data-building="${p.id}"><div><strong>${i+1}. ${p.name}</strong><div class="rankmeta">${p.holder} · +${p.ret}% 12M · Risiko ${p.risk}/5</div><div class="rankmeta">${p.occupied}/${p.slots} Slots belegt · ${free(p)} frei · Auktion ${p.lastAuctionDate}</div></div><div style="text-align:right"><div class="price">${chf(p.lastAuctionPrice)}</div><span class="rankfree ${free(p)===0?'full':''}">${free(p)?free(p)+' FREI':'AUSGEBUCHT'}</span></div></div>`).join('')}</div><p class="note">Letzte Auktionspreise sind Demo-Werte und digitale FinCity-Marktpreisreferenzen. Keine Bewertung der realen Immobilie.</p>`);panel.querySelectorAll('[data-building]').forEach(el=>el.onclick=()=>showBuilding(+el.dataset.building))}
function showPortfolio(){activeNav('portfolio');const bs=userBuildings(myPortfolio.user);const totalSlots=bs.reduce((a,b)=>a+b.slots,0),freeSlots=bs.reduce((a,b)=>a+free(b),0);openPanel(`<div class="eyebrow">MEIN PORTFOLIO · EIN USER · EIN DEPOT</div><h2>${myPortfolio.user}</h2><div class="grid2"><div class="metric"><span>GESAMTPORTFOLIO</span><strong>${chf(myPortfolio.capital)}</strong><div class="rankmeta">${myPortfolio.bank} · BEISPIEL-SCHNITTSTELLE</div></div><div class="metric"><span>USER-RENDITE · 12M</span><strong class="green">+${myPortfolio.ret}%</strong><div class="rankmeta">Risiko ${myPortfolio.risk}/5 · ${riskLabel(myPortfolio.risk)}</div></div></div><div class="card"><div class="eyebrow">GESAMT-ALLOKATION</div>${allocationHtml(myPortfolio.allocation)}</div><div class="card"><div class="eyebrow">MEINE GEBÄUDE</div><div class="previewrow"><span>${bs.length} Gebäude</span><b>${totalSlots} Slots · ${freeSlots} frei</b></div>${bs.map(b=>`<div class="owned-row" data-building="${b.id}"><span><strong>${b.name}</strong><div class="rankmeta">${b.occupied}/${b.slots} belegt · letzte Auktion ${chf(b.lastAuctionPrice)}</div></span><b>→</b></div>`).join('')}</div><div class="card"><strong>Ein User = ein Depot</strong><div class="note">Das investierte Kapital wird nicht auf Gebäude verteilt. Gebäude bilden Besitz-, Reputation- und Slot-Ebene ab.</div></div>`);panel.querySelectorAll('[data-building]').forEach(el=>el.onclick=()=>showBuilding(+el.dataset.building))}
function showRanking(){activeNav('ranking');const r=users().sort((a,b)=>b.ret-a.ret);openPanel(`<div class="eyebrow">FINCITY PERFORMANCE · USER-RANGLISTE</div><h2>🏆 Rendite-Rangliste</h2><p class="note">Ein User = ein Depot = eine Rendite. Ein User kann mehrere FinCity-Gebäude besitzen.</p><div class="card">${r.map((u,i)=>{const bs=userBuildings(u.holder);return `<div class="rankrow" data-user="${u.holder}"><b>#${i+1}</b><span><strong>${u.holder}</strong><div class="rankmeta">${u.buildings} Gebäude · ${u.slots} Slots · ${u.free} frei · Slot-Fee ${slotFee(u.ret)}% p.a.</div><div class="rankmeta">${bs.map(b=>b.name.replace('Mein Gebäude · ','')).join(' · ')}</div></span><span class="rankret">+${u.ret}%</span></div>`}).join('')}</div><p class="note">Ranking bewusst userbasiert. Gebäude sind Besitz- und Slot-Ebene; Performance stammt aus dem Partnerbank-Depot.</p>`);panel.querySelectorAll('[data-user]').forEach(el=>el.onclick=()=>showUser(el.dataset.user))}
function showUser(holder){const u=users().find(x=>x.holder===holder),bs=userBuildings(holder);if(!u)return;openPanel(`<div class="eyebrow">USER-PROFIL</div><h2>${holder}</h2><div class="grid2"><div class="metric"><span>12M RENDITE</span><strong class="green">+${u.ret}%</strong></div><div class="metric"><span>RISIKO</span><strong>${u.risk}/5</strong></div></div><div class="card"><strong>${bs.length} FinCity-Gebäude</strong>${bs.map(b=>`<div class="owned-row" data-building="${b.id}"><span>${b.name}<div class="rankmeta">${b.occupied}/${b.slots} Slots · ${free(b)} frei</div></span><b>→</b></div>`).join('')}</div><div class="card"><div class="previewrow"><span>Slot-Gebühr</span><b>${slotFee(u.ret)}% p.a.</b></div><div class="note">Gebühr basiert in dieser Demo auf der 12M-Performanceklasse des Strategie-Users.</div></div>${holder!==myPortfolio.user?'<button class="action" id="copyUser">SLOT MIETEN · USER-STRATEGIE KOPIEREN</button>':''}`);panel.querySelectorAll('[data-building]').forEach(el=>el.onclick=()=>showBuilding(+el.dataset.building));const c=document.getElementById('copyUser');if(c)c.onclick=()=>copyStrategy(holder)}
function showFees(){activeNav('fees');openPanel(`<div class="eyebrow">FINCITY PRICING v1</div><h2>Gebühren</h2><div class="card"><div class="previewrow"><span>Primärmarkt · City Drop</span><b>100 % → FinCity</b></div><div class="note">Der gesamte Zuschlagspreis eines neu herausgegebenen digitalen Gebäudes geht an FinCity.</div></div><div class="card"><div class="previewrow"><span>Sekundärmarkt</span><b>5 % Marketplace Fee</b></div><div class="note">Beispiel ${chf(2000)} Weiterverkauf → ${chf(1900)} Verkäufer, ${chf(100)} FinCity.</div></div><div class="card"><div class="previewrow"><span>Plattform</span><b>1,0 % p.a. Depotwert</b></div><div class="note">Beispiel ${chf(100000)} Depotwert → ${chf(1000)} pro Jahr an FinCity. Ein Depot pro User, einmal auf den Gesamtwert.</div></div><div class="card"><div class="eyebrow">SLOT-GEBÜHR → STRATEGIE-OWNER</div><div class="previewrow"><span>&lt;10 % Rendite</span><b>1 % p.a.</b></div><div class="previewrow"><span>10–&lt;20 %</span><b>2 % p.a.</b></div><div class="previewrow"><span>20–&lt;30 %</span><b>3 % p.a.</b></div><div class="previewrow"><span>≥30 %</span><b>4 % p.a. · Cap</b></div><div class="note">FinCity nimmt in Pricing v1 keinen zusätzlichen Anteil an der Slot-Gebühr.</div></div><div class="card"><strong>Partnerbank-Konditionen: separat / Demo-Annahme</strong><div class="note">Pricing-Hypothese. Rechtliche Einordnung, Steuern/VAT, FINMA-Fragen und Bankvertrag müssen vor Produktion validiert werden.</div></div>`)}
function showSystem(){activeNav('system');const won=trophies.filter(t=>t.champion);openPanel(`<div class="eyebrow">SYSTEM · CITY TROPHIES</div><h2>Zürich Trophy Network</h2><div class="grid2"><div class="metric"><span>TROPHÄEN</span><strong>${trophies.length}</strong></div><div class="metric"><span>BEREITS GEWONNEN</span><strong>${won.length}</strong></div></div><div class="card"><strong>Einmalige Trophy-Regel</strong><div class="note">Jede Trophy kann in der gesamten FinCity-Geschichte genau einmal gewonnen werden. Danach bleibt der Champion dauerhaft gespeichert. Pro Stadt höchstens eine noch freie Trophy pro Jahr; eine Trophy darf auch unvergeben bleiben.</div></div><div class="trophygrid">${trophies.map(t=>`<div class="trophy" data-trophy="${t.id}"><b>🏆 ${t.name}</b><div class="rankmeta">${t.subtype}</div><div class="rankmeta">${t.champion?`GEWONNEN ${t.champion.year} · ${t.champion.user}`:'OFFEN · EINMAL GEWINNBAR'}</div></div>`).join('')}</div><div class="card"><strong>Produktionslogik</strong><div class="note">Wohnungs-Slots sollen später über GWR/EGID verifiziert werden: 1 reale Wohnung = 1 FinCity-Slot. Nicht-Wohnobjekte wie Trophäen haben 0 Slots.</div></div>`);panel.querySelectorAll('[data-trophy]').forEach(el=>el.onclick=()=>showTrophy(+el.dataset.trophy))}
function showBuilding(id){const p=investment.find(x=>x.id===id);if(!p)return;safeFly(p.lng,p.lat);openPanel(`<div class="eyebrow">AKTIVES GEBÄUDE · USER-PERFORMANCE</div><h2>${p.name}</h2><div class="buildingphoto"></div><div class="grid2" style="margin-top:10px"><div class="metric"><span>USER</span><strong style="font-size:16px">${p.holder}</strong></div><div class="metric"><span>12M USER-RENDITE</span><strong class="green">+${p.ret}%</strong></div></div><div class="card"><div class="previewrow"><span>Risiko</span><b>${p.risk}/5 · ${riskLabel(p.risk)}</b></div><div class="previewrow"><span>Slots</span><b>${p.occupied}/${p.slots} belegt · ${free(p)} frei</b></div><div class="previewrow"><span>Slot-Gebühr</span><b>${slotFee(p.ret)}% p.a.</b></div><div class="previewrow"><span>Letzte Auktion</span><b>${chf(p.lastAuctionPrice)} · ${p.lastAuctionDate}</b></div></div><div class="card"><div class="eyebrow">USER-ALLOKATION</div>${allocationHtml(p.allocation)}</div>${p.holder===myPortfolio.user?'<button class="action" id="myPortfolioBtn">MEIN GESAMTPORTFOLIO →</button>':'<button class="action" id="copyBtn">SLOT MIETEN · USER-STRATEGIE KOPIEREN →</button>'}<p class="note">Das digitale FinCity-Gebäude repräsentiert keine Eigentumsrechte an der realen Immobilie.</p>`);const a=document.getElementById('myPortfolioBtn');if(a)a.onclick=showPortfolio;const c=document.getElementById('copyBtn');if(c)c.onclick=()=>copyStrategy(p.holder)}
function copyStrategy(holder){const u=users().find(x=>x.holder===holder);if(!u)return;const amount=5000,fee=slotFee(u.ret),annual=amount*fee/100;openPanel(`<div class="eyebrow">COPY-SIMULATION · KEINE ECHTE ORDER</div><h2>${holder} kopieren</h2><div class="card"><div class="previewrow"><span>Eigenes Kapital</span><b>${chf(amount)}</b></div><div class="previewrow"><span>Strategie-Rendite 12M</span><b>+${u.ret}%</b></div><div class="previewrow"><span>Slot-Gebühr</span><b>${fee}% p.a. · ca. ${chf(annual)}</b></div></div><div class="card"><strong>Dein Geld bleibt in deinem eigenen Depot</strong><div class="note">Die Strategie wird proportional im Depot des Mieters abgebildet. Es wird kein Kapital an den Strategie-Owner übertragen. Die Slot-Gebühr ist in dieser Demo dem Strategie-Owner zugeordnet.</div></div><div class="card">${allocationHtml(u.allocation)}</div><button class="action secondary" id="backRanking">ZUR USER-RANGLISTE</button>`);document.getElementById('backRanking').onclick=showRanking}
function showTrophy(id){const t=trophies.find(x=>x.id===id);if(!t)return;safeFly(t.lng,t.lat);openPanel(`<div class="eyebrow">CITY TROPHY · ${t.subtype}</div><h2>🏆 ${t.name}</h2><div class="card"><div class="previewrow"><span>Status</span><b>${t.champion?'DAUERHAFT VERGEBEN':'OFFEN'}</b></div>${t.champion?`<div class="previewrow"><span>Champion</span><b>${t.champion.user}</b></div><div class="previewrow"><span>Gewonnen</span><b>${t.champion.year}</b></div>`:'<div class="note">Diese Trophy kann genau einmal in der gesamten FinCity-Historie gewonnen werden.</div>'}</div><div class="card"><strong>0 Slots · nicht käuflich</strong><div class="note">Trophäen bilden Prestige und langfristige City-Historie ab.</div></div>`)}
function applyFilter(type){document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===type));markerRecords.forEach(r=>{let visible=type==='all'||r.type===type||(type==='active'&&r.type==='active');r.el.style.display=visible?'grid':'none';if(r.badge)r.badge.style.display=visible?'block':'none'})}
function safeFly(lng,lat){if(map)map.flyTo({center:[lng,lat],zoom:15.5,pitch:64,duration:900})}
function mapFallback(msg){const m=document.getElementById('map');m.innerHTML=`<div class="mapfallback"><b>Karte konnte nicht geladen werden</b>${msg}<br><br>Die FinCity-Menüs funktionieren trotzdem.</div>`}
function addMarker(obj,type){if(!map)return;const el=document.createElement('div');el.className=`marker ${type}`;el.textContent=type==='trophy'?'★':type==='auction'?'A':obj.id;const wrap=document.createElement('div');wrap.style.position='relative';wrap.appendChild(el);let badge=null;if(obj.slots){badge=document.createElement('div');badge.className='slot-badge';badge.textContent=free(obj);wrap.appendChild(badge)}const mk=new maplibregl.Marker({element:wrap,anchor:'bottom'}).setLngLat([obj.lng,obj.lat]).addTo(map);el.onclick=e=>{e.stopPropagation();if(type==='trophy')showTrophy(obj.id);else if(type==='auction')showAuction(obj.id);else showBuilding(obj.id)};markerRecords.push({mk,el:wrap,badge,type})}
function add3d(){if(!map)return;const layers=map.getStyle().layers||[];const labelId=layers.find(l=>l.type==='symbol'&&l.layout&&l.layout['text-field'])?.id;const source=Object.entries(map.getStyle().sources||{}).find(([,v])=>v.type==='vector')?.[0];if(!source)return;try{map.addLayer({id:'fincity-3d',source,'source-layer':'building',type:'fill-extrusion',minzoom:14,paint:{'fill-extrusion-color':'#c9ced8','fill-extrusion-height':['coalesce',['get','render_height'],['get','height'],12],'fill-extrusion-base':['coalesce',['get','render_min_height'],0],'fill-extrusion-opacity':.56}},labelId)}catch(e){console.warn('3D building layer skipped',e)}}
function satellite(){if(!map)return;try{if(!map.getSource('sat'))map.addSource('sat',{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'Tiles © Esri'});if(!map.getLayer('satbase')){const firstSymbol=(map.getStyle().layers||[]).find(l=>l.type==='symbol')?.id;map.addLayer({id:'satbase',type:'raster',source:'sat',paint:{'raster-opacity':.94}},firstSymbol)}satBtn.classList.add('active');mapBtn.classList.remove('active')}catch(e){console.warn(e)}}
function normalMap(){if(!map)return;if(map.getLayer('satbase'))map.removeLayer('satbase');mapBtn.classList.add('active');satBtn.classList.remove('active')}
function initMap(){if(!window.maplibregl){mapFallback('MapLibre wurde nicht geladen.');return}try{map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/bright',center:[8.5355,47.3744],zoom:13.6,pitch:62,bearing:-18,antialias:true});map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');map.on('load',()=>{satellite();add3d();investment.forEach(p=>addMarker(p,p.kind==='owned'?'owned':'active'));auctions.forEach(a=>addMarker(a,'auction'));trophies.forEach(t=>addMarker(t,'trophy'));applyFilter('all')});map.on('error',e=>console.warn('MapLibre',e?.error||e))}catch(e){console.error(e);mapFallback('Initialisierung fehlgeschlagen.')}}
function bind(){document.getElementById('trophyCount').textContent=trophies.length;document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='city')showCity();if(v==='auctions')showAuctions();if(v==='active')showActive();if(v==='portfolio')showPortfolio();if(v==='ranking')showRanking();if(v==='fees')showFees();if(v==='system')showSystem()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>applyFilter(b.dataset.filter));document.getElementById('portfolioTop').onclick=showPortfolio;satBtn.onclick=satellite;mapBtn.onclick=normalMap}
bind();initMap();
